#!/usr/pkg/bin/perl

use lib 'blib/lib';
use lib 'blib/arch';

use Kharon::utils qw/encode_var/;

use Kharon::Test::Entitlements;
use Kharon::Test::Parsing;
use Kharon::Test::ParseSpeed;
use Kharon::Test::Protocols;
use Kharon::Test::ForkClientServer;

eval {
	Kharon::Test::ParseSpeed::run_test();
};

if ($@) { print encode_var($@); exit(1); };
